---
# Nao tenho orgulho disso, mas, fica 5 segundos mais rapido na media
- hosts: all
  remote_user: root
  gather_facts: False
  pre_tasks:
   - set_fact: ansible_system=Linux
     when: inventory_hostname != 'nova-hpux'
   - set_fact: ansible_system=HP-UX
     when: inventory_hostname == 'nova-hpux'
  roles:
    - remote-config